export const SUGGESTED_GROUPS = [
  {
    id: "g1",
    name: "Iron Indoor Crew",
    members: 12,
    description: "Daily gym grinders",
    category: "gym",
    icon: "weight-lifter",
  },
  {
    id: "g2",
    name: "Lift Club",
    members: 8,
    description: "Strength training every day",
    category: "gym",
    icon: "dumbbell",
  },
  {
    id: "g3",
    name: "Road Runners",
    members: 15,
    description: "Rain or shine, we run",
    category: "running",
    icon: "run",
  },
  {
    id: "g4",
    name: "Trail Blazers",
    members: 9,
    description: "Outdoor cardio obsessives",
    category: "running",
    icon: "terrain",
  },
  {
    id: "g5",
    name: "Clean Eaters",
    members: 20,
    description: "Meal prep every Sunday",
    category: "nutrition",
    icon: "food-apple",
  },
  {
    id: "g6",
    name: "No Cheat Club",
    members: 11,
    description: "75 days, zero slip ups",
    category: "nutrition",
    icon: "silverware-variant",
  },
  {
    id: "g7",
    name: "High Vibes Only",
    members: 14,
    description: "Positive energy every day",
    category: "mindset",
    icon: "lightning-bolt",
  },
  {
    id: "g8",
    name: "Mental Gainers",
    members: 10,
    description: "Mind over matter",
    category: "mindset",
    icon: "brain",
  },
  {
    id: "g9",
    name: "10 Pages Daily",
    members: 7,
    description: "Non-fiction only",
    category: "reading",
    icon: "book-open-page-variant",
  },
  {
    id: "g13",
    name: "Football Fitness",
    members: 22,
    description: "Football drills as workouts",
    category: "sports",
    icon: "soccer",
  },
  {
    id: "g15",
    name: "Nature Walkers",
    members: 16,
    description: "30 mins outside every day",
    category: "outdoors",
    icon: "tree",
  },
];
