export const mockReflections = [
  // ─── User 1 (26 days) ───────────────────────────────────────────
  {
    user_id: 1,
    day_id: 1,
    mood_rating: 3,
    achievements: "Completed my workout and drank all my water.",
    challenges: "Struggled to stay off my phone in the evening.",
    next_day_focus: "Get to bed before 11pm and prep meals.",
    created_at: "2025-03-01T21:00:00.000Z",
  },
  {
    user_id: 1,
    day_id: 2,
    mood_rating: 4,
    achievements: "Got to bed on time and prepped meals for the next day.",
    challenges: "Felt groggy in the morning despite sleeping early.",
    next_day_focus: "Go for a morning walk before starting work.",
    created_at: "2025-03-02T21:00:00.000Z",
  },
  {
    user_id: 1,
    day_id: 3,
    mood_rating: 5,
    achievements: "Went for a morning walk and journalled.",
    challenges: "Afternoon slump hit hard after lunch.",
    next_day_focus: "Avoid heavy lunch and take a short walk after eating.",
    created_at: "2025-03-03T21:00:00.000Z",
  },
  {
    user_id: 1,
    day_id: 4,
    mood_rating: 2,
    achievements: "Stuck to my meal plan.",
    challenges: "Felt very anxious and distracted all day.",
    next_day_focus: "Start the morning with 10 minutes of meditation.",
    created_at: "2025-03-04T21:00:00.000Z",
  },
  {
    user_id: 1,
    day_id: 5,
    mood_rating: 3,
    achievements: "Meditated in the morning for the first time this week.",
    challenges: "Skipped the gym due to low energy.",
    next_day_focus: "Do a light workout even if energy is low.",
    created_at: "2025-03-05T21:00:00.000Z",
  },
  {
    user_id: 1,
    day_id: 6,
    mood_rating: 4,
    achievements: "Did a light workout and felt better afterwards.",
    challenges: "Spent too much time on social media before bed.",
    next_day_focus: "Put phone in another room 1 hour before sleep.",
    created_at: "2025-03-06T21:00:00.000Z",
  },
  {
    user_id: 1,
    day_id: 7,
    mood_rating: 4,
    achievements: "Phone-free evening and slept by 10:30pm.",
    challenges: "Felt restless during meditation.",
    next_day_focus: "Try a guided meditation instead of silent sitting.",
    created_at: "2025-03-07T21:00:00.000Z",
  },
  {
    user_id: 1,
    day_id: 8,
    mood_rating: 5,
    achievements: "Guided meditation was great, felt calm all morning.",
    challenges: "Work meeting ran long and disrupted my lunch break.",
    next_day_focus: "Block lunch break in calendar to protect the time.",
    created_at: "2025-03-08T21:00:00.000Z",
  },
  {
    user_id: 1,
    day_id: 9,
    mood_rating: 3,
    achievements: "Protected my lunch break and ate away from my desk.",
    challenges: "Felt socially drained after a long video call.",
    next_day_focus: "Schedule buffer time after long calls to decompress.",
    created_at: "2025-03-09T21:00:00.000Z",
  },
  {
    user_id: 1,
    day_id: 10,
    mood_rating: 4,
    achievements: "Took a 10-minute walk after a draining call.",
    challenges: "Craved junk food in the evening and gave in.",
    next_day_focus: "Prep a healthy snack in advance for the evening.",
    created_at: "2025-03-10T21:00:00.000Z",
  },
  {
    user_id: 1,
    day_id: 11,
    mood_rating: 3,
    achievements: "Had a healthy snack ready and avoided junk food.",
    challenges: "Woke up at 3am and couldn't fall back asleep.",
    next_day_focus: "Avoid screens after 9pm and try reading before bed.",
    created_at: "2025-03-11T21:00:00.000Z",
  },
  {
    user_id: 1,
    day_id: 12,
    mood_rating: 2,
    achievements: "Read before bed for the first time in months.",
    challenges: "Exhausted all day from broken sleep.",
    next_day_focus: "Prioritise rest and avoid overloading the schedule.",
    created_at: "2025-03-12T21:00:00.000Z",
  },
  {
    user_id: 1,
    day_id: 13,
    mood_rating: 4,
    achievements: "Kept the day light and napped for 20 minutes.",
    challenges: "Felt behind on tasks after a slow day.",
    next_day_focus: "Do a brain dump and prioritise top 3 tasks.",
    created_at: "2025-03-13T21:00:00.000Z",
  },
  {
    user_id: 1,
    day_id: 14,
    mood_rating: 5,
    achievements: "Crushed my top 3 tasks before noon.",
    challenges: "Overworked in the afternoon and skipped my walk.",
    next_day_focus: "Set a hard stop at 5pm and go outside.",
    created_at: "2025-03-14T21:00:00.000Z",
  },
  {
    user_id: 1,
    day_id: 15,
    mood_rating: 4,
    achievements: "Stopped work at 5pm and went for a 30-minute walk.",
    challenges: "Felt guilty stepping away even though work was done.",
    next_day_focus: "Remind myself that rest is productive.",
    created_at: "2025-03-15T21:00:00.000Z",
  },
  {
    user_id: 1,
    day_id: 16,
    mood_rating: 4,
    achievements: "Journalled about guilt around rest — felt freeing.",
    challenges: "Skipped strength training in favour of a walk again.",
    next_day_focus: "Alternate between walks and strength training.",
    created_at: "2025-03-16T21:00:00.000Z",
  },
  {
    user_id: 1,
    day_id: 17,
    mood_rating: 5,
    achievements: "Completed a full strength training session.",
    challenges: "Struggled to focus on creative work in the afternoon.",
    next_day_focus: "Schedule creative tasks in the morning when focus is high.",
    created_at: "2025-03-17T21:00:00.000Z",
  },
  {
    user_id: 1,
    day_id: 18,
    mood_rating: 3,
    achievements: "Did creative work first thing — most productive morning yet.",
    challenges: "Skipped meal prep and ended up ordering takeaway.",
    next_day_focus: "Spend 20 minutes on Sunday prepping snacks for the week.",
    created_at: "2025-03-18T21:00:00.000Z",
  },
  {
    user_id: 1,
    day_id: 19,
    mood_rating: 4,
    achievements: "Prepped snacks and lunches for the next 3 days.",
    challenges: "Felt unmotivated to exercise despite having the time.",
    next_day_focus: "Lay out gym clothes the night before as a visual cue.",
    created_at: "2025-03-19T21:00:00.000Z",
  },
  {
    user_id: 1,
    day_id: 20,
    mood_rating: 5,
    achievements: "Laid out clothes and made it to the gym first thing.",
    challenges: "Ran into a stressful situation with a friend.",
    next_day_focus: "Have an honest conversation to clear the air.",
    created_at: "2025-03-20T21:00:00.000Z",
  },
  {
    user_id: 1,
    day_id: 21,
    mood_rating: 3,
    achievements: "Had a difficult but honest conversation with my friend.",
    challenges: "Felt emotionally drained for the rest of the day.",
    next_day_focus: "Do something enjoyable and low-effort to recharge.",
    created_at: "2025-03-21T21:00:00.000Z",
  },
  {
    user_id: 1,
    day_id: 22,
    mood_rating: 4,
    achievements: "Watched a favourite film and fully switched off.",
    challenges: "Stayed up later than planned enjoying the downtime.",
    next_day_focus: "Set a wind-down alarm at 9:30pm.",
    created_at: "2025-03-22T21:00:00.000Z",
  },
  {
    user_id: 1,
    day_id: 23,
    mood_rating: 4,
    achievements: "Wind-down alarm worked — in bed by 10:15pm.",
    challenges: "Mind was racing with ideas and hard to switch off.",
    next_day_focus: "Keep a notepad by the bed to offload racing thoughts.",
    created_at: "2025-03-23T21:00:00.000Z",
  },
  {
    user_id: 1,
    day_id: 24,
    mood_rating: 5,
    achievements: "Notepad by the bed helped clear my mind instantly.",
    challenges: "Overscheduled the day and felt rushed.",
    next_day_focus: "Leave at least one hour unscheduled as buffer time.",
    created_at: "2025-03-24T21:00:00.000Z",
  },
  {
    user_id: 1,
    day_id: 25,
    mood_rating: 4,
    achievements: "Built buffer time into the day and felt much calmer.",
    challenges: "Forgot to drink enough water throughout the day.",
    next_day_focus: "Put a water bottle on the desk as a visual reminder.",
    created_at: "2025-03-25T21:00:00.000Z",
  },
  {
    user_id: 1,
    day_id: 26,
    mood_rating: 5,
    achievements: "Hit my water goal and felt more energised than usual.",
    challenges: "Hard to believe the 26 days are done — felt bittersweet.",
    next_day_focus: "Reflect on the full journey and set goals for next month.",
    created_at: "2025-03-26T21:00:00.000Z",
  },

  // ─── User 2 (10 days) ───────────────────────────────────────────
  {
    user_id: 2,
    day_id: 1,
    mood_rating: 2,
    achievements: "Showed up to work despite feeling low.",
    challenges: "Felt overwhelmed and didn't know where to start.",
    next_day_focus: "Write down just 3 small tasks to complete tomorrow.",
    created_at: "2025-03-01T21:00:00.000Z",
  },
  {
    user_id: 2,
    day_id: 2,
    mood_rating: 3,
    achievements: "Completed all 3 tasks on my short list.",
    challenges: "Still felt foggy and unfocused after lunch.",
    next_day_focus: "Try cutting out caffeine after 1pm.",
    created_at: "2025-03-02T21:00:00.000Z",
  },
  {
    user_id: 2,
    day_id: 3,
    mood_rating: 3,
    achievements: "No caffeine after 1pm and slept much better.",
    challenges: "Got into a negative headspace scrolling the news.",
    next_day_focus: "Delete news apps from the home screen.",
    created_at: "2025-03-03T21:00:00.000Z",
  },
  {
    user_id: 2,
    day_id: 4,
    mood_rating: 4,
    achievements: "Deleted news apps and replaced the time with a podcast.",
    challenges: "Missed a workout I had planned.",
    next_day_focus: "Schedule workouts like meetings — block the time.",
    created_at: "2025-03-04T21:00:00.000Z",
  },
  {
    user_id: 2,
    day_id: 5,
    mood_rating: 4,
    achievements: "Blocked workout time and actually showed up.",
    challenges: "Ate lunch at my desk and felt sluggish all afternoon.",
    next_day_focus: "Eat lunch away from the desk, even for 15 minutes.",
    created_at: "2025-03-05T21:00:00.000Z",
  },
  {
    user_id: 2,
    day_id: 6,
    mood_rating: 5,
    achievements: "Ate outside on a bench — felt refreshed afterwards.",
    challenges: "Evening routine fell apart after an unexpected call.",
    next_day_focus: "Build flexibility into the evening routine.",
    created_at: "2025-03-06T21:00:00.000Z",
  },
  {
    user_id: 2,
    day_id: 7,
    mood_rating: 4,
    achievements: "Kept a flexible routine and still hit the key habits.",
    challenges: "Felt lonely and isolated working from home.",
    next_day_focus: "Reach out to a friend or work from a café.",
    created_at: "2025-03-07T21:00:00.000Z",
  },
  {
    user_id: 2,
    day_id: 8,
    mood_rating: 5,
    achievements: "Worked from a café and had a great spontaneous chat.",
    challenges: "Productive but forgot to take breaks.",
    next_day_focus: "Set a timer to take a 5-minute break every hour.",
    created_at: "2025-03-08T21:00:00.000Z",
  },
  {
    user_id: 2,
    day_id: 9,
    mood_rating: 4,
    achievements: "Hourly breaks kept energy levels steady all day.",
    challenges: "Struggled to wind down and felt wired at bedtime.",
    next_day_focus: "Try a short stretching routine before bed.",
    created_at: "2025-03-09T21:00:00.000Z",
  },
  {
    user_id: 2,
    day_id: 10,
    mood_rating: 5,
    achievements: "Stretching routine before bed worked brilliantly.",
    challenges: "Realised how many good habits I had dropped before starting this.",
    next_day_focus: "Keep the momentum going and don't break the streak.",
    created_at: "2025-03-10T21:00:00.000Z",
  },
];
